name: PR Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Make env
      run: |
        python3 -m venv .env
        source ./.env/bin/activate
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        source ./.env/bin/activate
        pytest -vv --color=yes
    - name: Black - Code Formatting
      run: |
        source ./.env/bin/activate
        black --check .
      continue-on-error: false
    - name: Pylint - Static Analysis
      run: |
        source ./.env/bin/activate
        pylint $(find . -name "*.py" | tr '\n' ' ')
      continue-on-error: false
